// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TermStructure.Tests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class End_To_EndInterestRateCurveWorkflowsFeature : object, Xunit.IClassFixture<End_To_EndInterestRateCurveWorkflowsFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "BusinessWorkflows.feature"
#line hidden
        
        public End_To_EndInterestRateCurveWorkflowsFeature(End_To_EndInterestRateCurveWorkflowsFeature.FixtureData fixtureData, TermStructure_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "End-to-end interest rate curve workflows", "  As a portfolio manager\n  I want to build yield curves from market data\n  So tha" +
                    "t I can price instruments and evaluate economic signals", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Complete workflow - Bootstrap curve from bond data")]
        [Xunit.TraitAttribute("FeatureTitle", "End-to-end interest rate curve workflows")]
        [Xunit.TraitAttribute("Description", "Complete workflow - Bootstrap curve from bond data")]
        public void CompleteWorkflow_BootstrapCurveFromBondData()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Complete workflow - Bootstrap curve from bond data", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "BondId",
                            "MaturityYears",
                            "YieldToMaturity",
                            "AskPrice",
                            "CouponRate",
                            "CouponFrequency"});
                table1.AddRow(new string[] {
                            "BOND001",
                            "1",
                            "0.0425",
                            "99.75",
                            "0.04",
                            "2"});
                table1.AddRow(new string[] {
                            "BOND002",
                            "3",
                            "0.0460",
                            "98.80",
                            "0.045",
                            "2"});
                table1.AddRow(new string[] {
                            "BOND003",
                            "5",
                            "0.0480",
                            "98.50",
                            "0.048",
                            "2"});
                table1.AddRow(new string[] {
                            "BOND004",
                            "10",
                            "0.0500",
                            "97.00",
                            "0.05",
                            "2"});
#line 7
    testRunner.Given("I have a portfolio of bonds with varying maturities:", ((string)(null)), table1, "Given ");
#line hidden
#line 13
    testRunner.When("I bootstrap the zero-coupon yield curve from these bonds", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 14
    testRunner.And("I request interpolated yields at 2Y, 4Y, and 7Y", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 15
    testRunner.Then("I should receive a smoothly interpolated curve", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 16
    testRunner.And("the intermediate yields should remain smooth", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 17
    testRunner.And("I can use these rates for instrument pricing", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Detect curve inversion")]
        [Xunit.TraitAttribute("FeatureTitle", "End-to-end interest rate curve workflows")]
        [Xunit.TraitAttribute("Description", "Detect curve inversion")]
        public void DetectCurveInversion()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Detect curve inversion", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 19
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "Maturity",
                            "Rate"});
                table2.AddRow(new string[] {
                            "1",
                            "0.050"});
                table2.AddRow(new string[] {
                            "5",
                            "0.048"});
                table2.AddRow(new string[] {
                            "10",
                            "0.045"});
#line 20
    testRunner.Given("I have interest rates where:", ((string)(null)), table2, "Given ");
#line hidden
#line 25
    testRunner.When("I build the yield curve", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 26
    testRunner.Then("the system should detect an inverted yield curve", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 27
    testRunner.And("short-term rates should be higher than long-term rates", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 28
    testRunner.And("this is a signal of potential economic recession", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Price a bond using the constructed curve")]
        [Xunit.TraitAttribute("FeatureTitle", "End-to-end interest rate curve workflows")]
        [Xunit.TraitAttribute("Description", "Price a bond using the constructed curve")]
        public void PriceABondUsingTheConstructedCurve()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Price a bond using the constructed curve", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 30
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "Maturity",
                            "Rate"});
                table3.AddRow(new string[] {
                            "1",
                            "0.025"});
                table3.AddRow(new string[] {
                            "5",
                            "0.030"});
                table3.AddRow(new string[] {
                            "10",
                            "0.035"});
#line 31
    testRunner.Given("I have a built yield curve from market data:", ((string)(null)), table3, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "Property",
                            "Value"});
                table4.AddRow(new string[] {
                            "Coupon Rate",
                            "0.04"});
                table4.AddRow(new string[] {
                            "Time to Maturity",
                            "7"});
                table4.AddRow(new string[] {
                            "Par Value",
                            "100"});
                table4.AddRow(new string[] {
                            "Coupon Frequency",
                            "2"});
#line 36
    testRunner.And("I want to price a bond with:", ((string)(null)), table4, "And ");
#line hidden
#line 42
    testRunner.When("I use the curve to discount cash flows", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 43
    testRunner.Then("I should calculate the bond\'s present value", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 44
    testRunner.And("the bond price should reflect the current yield curve", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 45
    testRunner.And("the price should be different from par value", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Densify a sparse bootstrapped curve")]
        [Xunit.TraitAttribute("FeatureTitle", "End-to-end interest rate curve workflows")]
        [Xunit.TraitAttribute("Description", "Densify a sparse bootstrapped curve")]
        public void DensifyASparseBootstrappedCurve()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Densify a sparse bootstrapped curve", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 47
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "Maturity",
                            "Rate"});
                table5.AddRow(new string[] {
                            "1",
                            "0.025"});
                table5.AddRow(new string[] {
                            "5",
                            "0.030"});
                table5.AddRow(new string[] {
                            "10",
                            "0.035"});
#line 48
    testRunner.Given("I have a bootstrapped yield curve with sparse points:", ((string)(null)), table5, "Given ");
#line hidden
#line 53
    testRunner.When("I densify the curve with daily (0.00274 year) intervals", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 54
    testRunner.Then("I should receive approximately 3,285 yield points", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 55
    testRunner.And("each point should have a unique maturity", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 56
    testRunner.And("the curve should be continuous and smooth", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                End_To_EndInterestRateCurveWorkflowsFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                End_To_EndInterestRateCurveWorkflowsFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
