// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TermStructure.Tests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class BuildingInterestRateCurvesWithDifferentStrategiesFeature : object, Xunit.IClassFixture<BuildingInterestRateCurvesWithDifferentStrategiesFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CurveBuilding.feature"
#line hidden
        
        public BuildingInterestRateCurvesWithDifferentStrategiesFeature(BuildingInterestRateCurvesWithDifferentStrategiesFeature.FixtureData fixtureData, TermStructure_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Building interest rate curves with different strategies", "  As a portfolio manager\n  I want to build yield curves using different construct" +
                    "ion strategies\n  So that I can price instruments and perform risk analysis with " +
                    "the most appropriate method", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
  #line hidden
#line 7
    testRunner.Given("the interpolation strategy is linear interpolation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 8
    testRunner.And("the system is ready to build curves", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Build a yield curve using bootstrap strategy with valid bonds")]
        [Xunit.TraitAttribute("FeatureTitle", "Building interest rate curves with different strategies")]
        [Xunit.TraitAttribute("Description", "Build a yield curve using bootstrap strategy with valid bonds")]
        public void BuildAYieldCurveUsingBootstrapStrategyWithValidBonds()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Build a yield curve using bootstrap strategy with valid bonds", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 10
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
  this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                            "BondId",
                            "MaturityYears",
                            "YieldToMaturity",
                            "AskPrice",
                            "CouponRate",
                            "CouponFrequency"});
                table6.AddRow(new string[] {
                            "BOND001",
                            "1",
                            "0.0425",
                            "99.75",
                            "0.04",
                            "2"});
                table6.AddRow(new string[] {
                            "BOND002",
                            "5",
                            "0.0480",
                            "98.50",
                            "0.045",
                            "2"});
                table6.AddRow(new string[] {
                            "BOND003",
                            "10",
                            "0.0500",
                            "97.00",
                            "0.05",
                            "2"});
#line 11
    testRunner.Given("I have bond quotes with the following details:", ((string)(null)), table6, "Given ");
#line hidden
#line 16
    testRunner.And("I use the bootstrap curve building strategy", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 17
    testRunner.When("I build the yield curve from these bonds", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 18
    testRunner.Then("the curve should contain 3 yield points", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 19
    testRunner.And("the curve should be sorted by maturity in ascending order", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 20
    testRunner.And("the first point should have maturity 1 year", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 21
    testRunner.And("the last point should have maturity 10 years", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 22
    testRunner.And("all yields should be positive", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Build a yield curve using linear strategy with interest rate data")]
        [Xunit.TraitAttribute("FeatureTitle", "Building interest rate curves with different strategies")]
        [Xunit.TraitAttribute("Description", "Build a yield curve using linear strategy with interest rate data")]
        public void BuildAYieldCurveUsingLinearStrategyWithInterestRateData()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Build a yield curve using linear strategy with interest rate data", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 24
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
  this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                            "Tenor",
                            "Rate"});
                table7.AddRow(new string[] {
                            "1Y",
                            "2.50"});
                table7.AddRow(new string[] {
                            "2Y",
                            "2.75"});
                table7.AddRow(new string[] {
                            "5Y",
                            "3.00"});
                table7.AddRow(new string[] {
                            "10Y",
                            "3.15"});
#line 25
    testRunner.Given("I have the following interest rate observations:", ((string)(null)), table7, "Given ");
#line hidden
#line 31
    testRunner.And("I use the linear curve building strategy", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 32
    testRunner.When("I build the yield curve from these rates", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 33
    testRunner.Then("the curve should contain 4 yield points", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 34
    testRunner.And("the curve should be sorted by maturity in ascending order", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 35
    testRunner.And("the point at 1 year should have rate approximately 0.0250", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 36
    testRunner.And("the point at 10 years should have rate approximately 0.0315", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Build a yield curve using Nelson-Siegel strategy with calibration")]
        [Xunit.TraitAttribute("FeatureTitle", "Building interest rate curves with different strategies")]
        [Xunit.TraitAttribute("Description", "Build a yield curve using Nelson-Siegel strategy with calibration")]
        public void BuildAYieldCurveUsingNelson_SiegelStrategyWithCalibration()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Build a yield curve using Nelson-Siegel strategy with calibration", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 38
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
  this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                            "Tenor",
                            "Rate"});
                table8.AddRow(new string[] {
                            "1Y",
                            "2.50"});
                table8.AddRow(new string[] {
                            "5Y",
                            "3.00"});
                table8.AddRow(new string[] {
                            "10Y",
                            "3.15"});
                table8.AddRow(new string[] {
                            "20Y",
                            "3.25"});
#line 39
    testRunner.Given("I have the following interest rate observations for Nelson-Siegel:", ((string)(null)), table8, "Given ");
#line hidden
#line 45
    testRunner.And("I use the Nelson-Siegel curve building strategy with lambda 0.5", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 46
    testRunner.When("I build the yield curve from these rates", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 47
    testRunner.Then("the curve should contain at least 50 yield points", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 48
    testRunner.And("the curve should be smooth and differentiable", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 49
    testRunner.And("the curve should respect the observed rates at the input tenors", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Interpolate yields at intermediate maturities")]
        [Xunit.TraitAttribute("FeatureTitle", "Building interest rate curves with different strategies")]
        [Xunit.TraitAttribute("Description", "Interpolate yields at intermediate maturities")]
        public void InterpolateYieldsAtIntermediateMaturities()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Interpolate yields at intermediate maturities", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 51
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
  this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                            "Maturity",
                            "Rate"});
                table9.AddRow(new string[] {
                            "1",
                            "0.025"});
                table9.AddRow(new string[] {
                            "5",
                            "0.030"});
                table9.AddRow(new string[] {
                            "10",
                            "0.035"});
#line 52
    testRunner.Given("I have a yield curve with the following points:", ((string)(null)), table9, "Given ");
#line hidden
#line 57
    testRunner.When("I request the interpolated yield at maturity 3 years", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 58
    testRunner.Then("the interpolated rate should be approximately 0.0275", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 59
    testRunner.And("the rate should be between the rates at 1 year and 5 years", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Densify a sparse curve into daily points")]
        [Xunit.TraitAttribute("FeatureTitle", "Building interest rate curves with different strategies")]
        [Xunit.TraitAttribute("Description", "Densify a sparse curve into daily points")]
        public void DensifyASparseCurveIntoDailyPoints()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Densify a sparse curve into daily points", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 61
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
  this.FeatureBackground();
#line hidden
#line 62
    testRunner.Given("I have a yield curve with 3 points from 1 to 10 years", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 63
    testRunner.When("I densify the curve with a step of 0.25 years (quarterly)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 64
    testRunner.Then("the output curve should contain at least 37 points", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 65
    testRunner.And("all maturities should be evenly spaced", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 66
    testRunner.And("the first point should have maturity 1 year", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 67
    testRunner.And("the last point should have maturity 10 years", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Get interpolated rate at arbitrary maturity")]
        [Xunit.TraitAttribute("FeatureTitle", "Building interest rate curves with different strategies")]
        [Xunit.TraitAttribute("Description", "Get interpolated rate at arbitrary maturity")]
        public void GetInterpolatedRateAtArbitraryMaturity()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get interpolated rate at arbitrary maturity", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 69
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
  this.FeatureBackground();
#line hidden
#line 70
    testRunner.Given("I have built a yield curve from valid bonds using bootstrap", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 71
    testRunner.And("the curve has points at 1Y, 5Y, and 10Y", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 72
    testRunner.When("I request the interpolated yield at 7.5 years", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 73
    testRunner.Then("the system should return a decimal rate value", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 74
    testRunner.And("the rate should be between the 5Y and 10Y rates", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 75
    testRunner.And("the rate should be closer to the 10Y rate than the 1Y rate", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Build curves with different tenor combinations")]
        [Xunit.TraitAttribute("FeatureTitle", "Building interest rate curves with different strategies")]
        [Xunit.TraitAttribute("Description", "Build curves with different tenor combinations")]
        [Xunit.InlineDataAttribute("1Y", "5Y", "10Y", "3.0", "3", new string[0])]
        [Xunit.InlineDataAttribute("6M", "1Y", "2Y", "2.5", "3", new string[0])]
        [Xunit.InlineDataAttribute("2Y", "7Y", "30Y", "3.5", "3", new string[0])]
        [Xunit.InlineDataAttribute("3M", "6M", "1Y", "2.0", "3", new string[0])]
        public void BuildCurvesWithDifferentTenorCombinations(string tenor1, string tenor2, string tenor3, string yield_Value, string expected_Points, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("tenor1", tenor1);
            argumentsOfScenario.Add("tenor2", tenor2);
            argumentsOfScenario.Add("tenor3", tenor3);
            argumentsOfScenario.Add("yield_value", yield_Value);
            argumentsOfScenario.Add("expected_points", expected_Points);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Build curves with different tenor combinations", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 77
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
  this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                            "Tenor"});
                table10.AddRow(new string[] {
                            string.Format("{0}", tenor1)});
                table10.AddRow(new string[] {
                            string.Format("{0}", tenor2)});
                table10.AddRow(new string[] {
                            string.Format("{0}", tenor3)});
#line 78
    testRunner.Given("I have interest rate observations for the following tenors:", ((string)(null)), table10, "Given ");
#line hidden
#line 83
    testRunner.And(string.Format("each tenor has an observed yield of {0} percent", yield_Value), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 84
    testRunner.And("I use the linear curve building strategy", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 85
    testRunner.When("I build the yield curve", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 86
    testRunner.Then(string.Format("the curve should contain {0} yield points", expected_Points), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 87
    testRunner.And("all maturities should be in ascending order", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Build curve respects bond maturity ordering")]
        [Xunit.TraitAttribute("FeatureTitle", "Building interest rate curves with different strategies")]
        [Xunit.TraitAttribute("Description", "Build curve respects bond maturity ordering")]
        public void BuildCurveRespectsBondMaturityOrdering()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Build curve respects bond maturity ordering", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 96
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
  this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                            "BondId",
                            "MaturityYears",
                            "AskPrice"});
                table11.AddRow(new string[] {
                            "BOND003",
                            "10",
                            "97.00"});
                table11.AddRow(new string[] {
                            "BOND001",
                            "1",
                            "99.75"});
                table11.AddRow(new string[] {
                            "BOND002",
                            "5",
                            "98.50"});
#line 97
    testRunner.Given("I provide bonds in random order:", ((string)(null)), table11, "Given ");
#line hidden
#line 102
    testRunner.And("I use the bootstrap curve building strategy", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 103
    testRunner.When("I build the yield curve", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 104
    testRunner.Then("the output curve should automatically sort points by maturity ascending", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 105
    testRunner.And("the first point should have maturity 1 year", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 106
    testRunner.And("the middle point should have maturity 5 years", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 107
    testRunner.And("the last point should have maturity 10 years", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                BuildingInterestRateCurvesWithDifferentStrategiesFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                BuildingInterestRateCurvesWithDifferentStrategiesFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
